---
name: BirbBot
description: A sample command-line application.
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  nyxx:
    git:
      url: https://github.com/Calamity210/nyxx
  Birb:
    git:
      url: https://github.com/Calamity210/BirbLang
  http: ^0.12.2
dev_dependencies:
  dart_style:
  analyzer:
