---
name: BirbBot
description: A sample command-line application.
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  nyxx: ^0.30.0
  Birb:
    git:
      url: https://github.com/Calamity210/BirbLang
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
